name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build Gradle
      - name: Build with Gradle
        run: ./gradlew clean build

      # Step 4: Run Spring Boot
      - name: Start Spring Boot
        run: ./gradlew bootRun &
        env:
          SPRING_PROFILES_ACTIVE: test

      # Step 5: Wait for Spring Boot
      - name: Wait for Spring Boot to start
        run: sleep 7

      # Step 6: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 7: Install Postman CLI
      - name: Install Postman CLI
        run: |
          curl -L https://dl-cli.pstmn.io/install/linux64.sh | sh

      # Step 8: Login to Postman CLI
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POST_SECRECT }}

      # Step 9: Run Postman Collection via CLI
      - name: Run API Tests
        run: |
          postman collection run "33013225-d627df5f-6fa0-444b-a73f-b9edeff3a3d8" \
          --environment ./Postman/url.postman_environment.json

      # Step 10: Save reports
      - name: Saving execution reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: newman-execution-report
          path: newman/report.html
          retention-days: 30
