name: Run Postman Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install Newman
      - name: Install Newman
        run: npm install -g newman

      # Step 4: Run Newman with your Postman collection
      - name: Run Postman Collection
        run: |
          mkdir -p newman
          newman run ./Postman/user-tests.postman_collection.json \
            --environment ./Postman/url.postman_environment.json \
            --reporters cli,html
            --reporter-html-export newman/newman-run-report.html

      # Step 5: Upload Newman HTML Report
      - name: Upload Newman HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: newman-html-report
          path: newman/newman-run-report.html